### 获取用户信息 by 8088
GET http://localhost:8088/?id=101

### 获取用户信息
POST http://localhost:8081
Content-Type: application/json

{
  "service": "com.kai.kairpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}

### 获取用户信息
POST http://localhost:8081
Content-Type: application/json

{
  "service": "com.kai.kairpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [200, "Kai"]
}

### 获取订单信息
POST http://localhost:8081
Content-Type: application/json

{
"service": "com.kai.kairpc.demo.api.OrderService",
"method": "findById",
"args": [100]
}

### 甚至可以访问 toString 方法，这是不对的
POST http://localhost:8080
Content-Type: application/json

{
  "service": "com.kai.kairpc.demo.api.OrderService",
  "method": "toString",
  "args": []
}
