server:
  port: 8088

kairpc:
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zkServer: localhost:2181
  zkRoot: kairpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000

logging:
  level:
    root: error
    com.kai.kairpc: debug