server:
  port: 8081

kairpc:
  zk:
    server: localhost:2181
    root: kairpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      unit: B001
      gray: false

logging:
  level:
    root: error
    com.kai.kairpc: info